name = "essaycoach-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Bindings
[vars]
APP_URL = "https://alfons149-cmyk.github.io/essay-coach-instant"

# Add your Stripe price IDs
STRIPE_PRICE_MONTH = "price_xxx_month_15_eur"
STRIPE_PRICE_SEMESTER = "price_yyy_6months_75_eur"

# KV for entitlements
[[kv_namespaces]]
binding = "KV_ENTITLEMENTS"
id = "kv_entitlements_prod"      # create via wrangler or dashboard

# Secrets you will set with `wrangler secret put ...`
# OPENAI_API_KEY
# STRIPE_SECRET
# STRIPE_WEBHOOK_SECRET
